logging:
    level:
        root: WARN
        org.springframework.web.servlet.mvc: INFO
        com.fasterxml.jackson.datatype: INFO
info:
  app:
    name: "Submissões de Artigos"
    description: "Projeto para submissões de artigos científicos em eventos"
    version: "0.0.1.SNAPSHOT"

spring:
  h2:
    console:
      enabled: true
      path: "/h2"
  datasource:
    url: "jdbc:h2:file:~/db/submissoes"
    username: "sa"
    password:
    driver-class-name: org.h2.Driver
  thymeleaf:
    mode: html
    cache: false
  jackson:
    deserialization:
      fail-on-unknown-properties: true
    date-format: yyyy-MM-dd
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "health, env, metrics, sessions, mappings, info, liquibase"
